public class CreateTaskForOppBatch implements Database.Batchable<sObject>, database.stateful{ 
           
    public Database.QueryLocator start(Database.BatchableContext bc){ 
            
        }
    
    public void execute(Database.BatchableContext bc, list<account>scope){
           
          
          
         
         }  
     
  
        public void finish(Database.BatchableContext bc){
        
        }
    }
    