Greetings g1 = new Greetings();
g1.language = 'Hindi';
string g1Greet = g1.greetHello(10);
System.debug(g1Greet);

Greetings g2 = new Greetings();
g2.language = 'English';
string g2Greet = g2.greetHello(11);
System.debug(g2Greet);

Greetings g3 = new Greetings();
g3.language = 'Turkish';
string g3Greet = g3.greetHello(12);
System.debug(g3Greet);

Greetings g4 = new Greetings();
g4.language = 'Russian';
string g4Greet = g4.greetHello(13);
System.debug(g4Greet);