List<string> shopList = new List<string>{'lkmclmlslkd','lskdnclk','gdhsjkk','mccdldll','iiksk'};
shopList.add('Book');
shopList.add('tablet');
shopList.add('Pjomr');
shopList.add('Apple');

System.debug(shopList);

List<date> birthdateList = new List<date>{date.newInstance(1977, 9, 13), date.newInstance(1980, 2, 12), date.newInstance(1972, 11, 13)};
birthdateList.sort();
System.debug(birthdateList);